lydia-samir submit homework database week1
HackYourHomework/databases-class34 pull request #6
Opened 2022-01-17 20:10 UTC by Lydia-GG

2022-01-20 20:20 UTC, GinaSt requested changes
Hi Lydia! Your work is almost done! I see you have understood the basic SQL queries and how to create and populate a table. However, you could try to add primary and and foreign keys to your tables.

2022-01-20 20:20 UTC, GinaSt commented on Week1/ex1.js
> +  'CREATE TABLE Invitee (invitee_no INT, invitee_name VARCHAR(100), invited_by VARCHAR(100))',
In this table you need a Primary key.

2022-01-20 20:20 UTC, GinaSt commented on Week1/ex1.js
> +  'CREATE TABLE Meeting (meeting_no INT, meeting_title VARCHAR(100), starting_time TIME, ending_time TIME,room_no INT)',
Here there is a relationship between the Meeting table and the Room table. Is there a way to show this relationship. 
HINT: Try to add primary keys to both tables.

2022-01-20 20:20 UTC, GinaSt commented on Week1/ex2.js
> +let queries = [
Nice and clean queries!

2022-01-20 20:20 UTC, GinaSt commented on Week1/ex1.js
> +  `INSERT INTO room (room_no, room_name, floor_number) VALUES (1,'Training Room', 1),(2,'Leadership',1),(3,'Conference',1),(4,'Triumph',2),(5,'Inspiration',2)`,
Nice that you insert multiple rows with one query!

2022-01-20 20:20 UTC, GinaSt commented on Week1/ex1.js
> +connection.query(
You could have a function to run all the create queries instead of rewriting the code.

2022-01-21 17:57 UTC, GinaSt approved these changes
Nicely done :)

2022-01-22 15:16 UTC, Lydia-GG commented
> Nicely done :)

thank you so much for your review and time @GinaSt. the code became more readable because of you .

2022-01-27 08:37 UTC, closed without merging